name: SkyMines
main: me.LavaBa11.SkyMines
version: 1.0
author: LavaBa11, Cloaking_Ocean
depend: [WorldGuard]
commands:
   skymines:
      description: SkyMines Help.
      usage: /<command>
   coalsell:
      description: Sell Coal.
      usage: /<command>
      aliases: [csell, sellc]
   command:
      description: Blank description.
      usage: /<command>
   command:
      description: Blank description.
      usage: /<command>