name: SkyMines
main: me.LavaBa11.SkyMines
version: 1.0
author: LavaBa11, Cloaking_Ocean
depend: [WorldGuard]
commands:
   skymines:
      description: SkyMines Help.
   coalsell:
      description: Sell Coal.
      aliases: [csell, sellc]
   ironsell:
      description: Sell Iron.
      aliases: [isell, selli]
   lapissell:
      description: Sell Lapis Luzuli.
      aliases: [lsell, selll]