name: SkyMines
main: me.LavaBa11.SkyMines
version: 1.0
author: LavaBa11, Cloaking_Ocean
depend: [WorldGuard]
commands:
   skymines:
      description: SkyMines Help.
   coalsell:
      description: Sell Coal.
      aliases: [csell, sellc, cs]
   ironsell:
      description: Sell Iron.
      aliases: [isell, selli, irs]
   goldsell:
      description: Sell Gold Ingots.
      aliases: [gsell, sellg, gs]
   diamondsell:
      description: Sell Diamonds.
      aliases: [dsell, selld, ds]
   emeraldsell:
      description: Sell Emeralds.
      aliases: [esell, selle, es]
   lapissell:
      description: Sell Lapis Luzuli.
      aliases: [lsell, selll, las]
   luckyorb:
      description: Get A Lucky Orb.
      aliases: [lorb]
   creditegg:
      description: Get A Credit Egg.
      aliases: [cregg]
   virtualanvil:
      description: Opens A Virual Anvil.
      aliases: [va, anvilv, av, vanvil]
   website:
      description: The SkyMines Website!
      aliases: [web]
   forums:
      description: The SkyMines Forums!
      aliases: [forum]