name: 
main: me.LavaBa11.
version: 1.0
author: LavaBa11
depend: [WorldGuard]
commands:
   command:
      description: Blank description.
      usage: /<command>
   command:
      description: Blank description.
      usage: /<command>
   command:
      description: Blank description.
      usage: /<command>
   command:
      description: Blank description.
      usage: /<command>