name: SkyMines
main: me.LavaBa11.SkyMines
version: 1.0
author: LavaBa11, Cloaking_Ocean
commands:
   command:
      description: Blank description.
      usage: /<command>
   command:
      description: Blank description.
      usage: /<command>
   command:
      description: Blank description.
      usage: /<command>
   command:
      description: Blank description.
      usage: /<command>